-- Run this entire file in Supabase Dashboard > SQL Editor.

CREATE TABLE IF NOT EXISTS public.library_status (
  id smallint PRIMARY KEY DEFAULT 1 CHECK (id = 1),
  is_open boolean NOT NULL DEFAULT false,
  updated_at timestamptz NOT NULL DEFAULT now()
);

INSERT INTO public.library_status (id, is_open)
VALUES (1, false)
ON CONFLICT (id) DO NOTHING;

CREATE TABLE IF NOT EXISTS public.activity_log (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username varchar(50) NOT NULL
    CHECK (char_length(btrim(username)) BETWEEN 1 AND 50),
  action text NOT NULL CHECK (action IN ('opened', 'closed')),
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS activity_log_created_at_idx
  ON public.activity_log (created_at DESC, id DESC);

-- The browser never talks directly to these tables. With RLS enabled and no
-- policies, Supabase's public API roles cannot read or modify them. The trusted
-- backend connection continues to work as the database owner.
ALTER TABLE public.library_status ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.activity_log ENABLE ROW LEVEL SECURITY;
